package:
  name: ANNOgesic
  version: 0.7.20

requirements:
  build:
    - python
    - pip
    - blast
    - transtermhp
    - viennarna
    - intarna
    - samtools
    - bcftools
    - segemehl
    - meme
    - infernal

summary: RNA-Seq annotation tool for bacteria
