package:
  name: ANNOgesic
  version: 0.7.20

requirements:
  build:
    - python
    - pip
    - blast
    - transtermhp
    - viennarna
    - intarna
    - samtools
    - bcftools
    - segemehl
    - meme
    - infernal

test:
    commands:
       - annogesic --version

about:
  home: https://github.com/Sung-Huan/ANNOgesic
  license: ISC
  summary: bacterial RNA-Seq annotation tool
