package:
    name: tsspredator
    version: 1.06

source:
    url: https://lambda.informatik.uni-tuebingen.de/nexus/content/repositories/releases/org/uni-tuebingen/it/TSSpredator/1.06/TSSpredator-1.06.jar

summary: Transcriptional start site prediction tool
