package:
  name: hicexplorer
  version: '2.1.2'

source:
  fn: 2.1.2.tar.gz
  url: https://github.com/deeptools/HiCExplorer/archive/2.1.2.tar.gz
  sha256: 37df3ef3816769165f86ce1bc4873935a7d409cc5447a91f475835effd004570

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy 1.13.*
    - scipy 1.0.*
    - matplotlib 2.1.*
    - pysam
    - intervaltree
    - biopython >=1.68
    - pytables
    - pybigwig
    - pandas
    - jinja2
    - configparser >=3.5.*  # [not py>34]
    - cooler <=0.7.6
    - six
    - future
    - unidecode
  run:
    - python
    - numpy 1.13.*
    - scipy 1.0.*
    - matplotlib 2.1.*
    - pysam
    - intervaltree
    - biopython >=1.68
    - pytables
    - pybigwig
    - pandas
    - jinja2
    - configparser >=3.5.*  # [not py>34]
    - cooler <=0.7.6
    - six
    - future
    - unidecode

test:
  imports:
    - hicexplorer

  commands:
    - hicBuildMatrix --version
    - hicCorrelate --version

about:
  home: https://github.com/deeptools/HiCExplorer
  license: GPL3
  summary: Set of programs to process, analyze and visualize Hi-C data
